# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@3.2
  aws-ecr: circleci/aws-ecr@8.2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
workflows:
    buildDockerImageandPush:
      jobs:
        - aws-ecr/build-and-push-image:
            context: AWS
            region: eu-central-1
            repo: marqoola-ui
            tag: latest
            push-image: true
        - aws-ecs/deploy-service-update:
            cluster: mqCluster
            context: AWS
            container-image-name-updates: container=marqoola-ui,tag=latest
            family: marqoola-ui
            requires:
              - aws-ecr/build-and-push-image

